Upskillz.Web/Models/AddSamuraiViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Upskillz.Web.Models
{
    public class AddSamuraiViewModel
    {
        [Required(ErrorMessage = "This field is required")]
        [StringLength(50)]
        public string Name { get; set; }
        public string ImageUrl { get; set; } = "https://cdn.dribbble.com/users/145072/screenshots/4258729/samuraidrib_copy.jpg";    

        [Required(ErrorMessage = "This field is required")]
        public string ShortStory { get; set; }

        [Required(ErrorMessage = "Please enter a quote for the legend")]
        public string Quote { get; set; }
    }
}

Upskillz.Web/Models/SamuraiViewModel.cs
using System.Collections.Generic;
using Upskillz.Models;

namespace Upskillz.Web.Models
{
    public class SamuraiViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Story { get; set; }
        public List<Quote> Quotes { get; set; }
        public List<Battle> Battles { get; set; }
    }
}

Upskillz.Web/Controllers/SamuraiController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Linq;
using System.Threading.Tasks;
using Upskillz.Core.Interfaces;
using Upskillz.Data.Abstractions;
using Upskillz.Models;
using Upskillz.Models.Dtos.Samurai;
using Upskillz.Web.Helpers;
using Upskillz.Web.Models;
using static Upskillz.Web.Helpers.HtmlUtility;

namespace Upskillz.Web.Controllers
{
    public class SamuraiController : Controller
    {
        private readonly ISamuraiService _samuraiService;
        private readonly IMapper _mapper;

        public SamuraiController(ISamuraiService samuraiService, IMapper mapper)
        {
            _mapper = mapper;
            _samuraiService = samuraiService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AllSamurais(string searchTerm = null)
        {
            if(searchTerm == null)
            {
                var samuraisTask = await _samuraiService.GetSamurais();
                var samurais = samuraisTask.Data;
                return View(samurais);
            }
            var searchResultTask = await _samuraiService.Search(searchTerm);
            var searchResult = searchResultTask.Data;

            bool isAjax = HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest";

            if (isAjax)
                return PartialView("_SamuraiList", searchResult);
            else
                return View(searchResult);

        }


        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult AddSamurai()
        {
            var model = new AddSamuraiViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [NoDirectAccess]
        public async Task<IActionResult> AddSamurai(AddSamuraiViewModel model)
        {
            if (ModelState.IsValid)
            {
                var addSamuraiDto = _mapper.Map<AddSamuraiDto>(model);
                var response = await _samuraiService.AddSamurai(addSamuraiDto);
                if (response.Succeeded)
                {
                    var data = await _samuraiService.GetSamurais();
                    var samurais = data.Data;
                    return Json(new { isValid = true, html = HtmlUtility.RenderRazorViewToString(this, "_SamuraiList", samurais) });
                }
                ModelState.AddModelError("", response.Message);
            }
            return View(model);
            
        }


        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Autocomplete(string term)
        {
            var samuraisTask = await _samuraiService.QuickSearch(term);
            var samurais = samuraisTask.Data;
            var model = samurais.Select(r => new
            {
                label = r.Name
            });
            return Json(model, new JsonSerializerSettings());
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> SamuraiDetails(string samuraiId)
        {
            var samuraiTask = await _samuraiService.GetSamurai(samuraiId);
            var samurai = samuraiTask.Data;
            if(samurai != null)
            {
                var model = new SamuraiViewModel
                {
                    Id = samurai.Id,
                    Name = samurai.Name,
                    ImageUrl = samurai.ImageUrl,
                    Story = samurai.ShortStory,
                    Quotes = samurai.Quotes,
                    Battles = samurai.Battles
                };
                return View(model);
            }
            return NotFound();
        }
    }
}

Upskillz.Web/Views/Samurai/AddSamurai.cshtml
@model AddSamuraiViewModel

@{
    ViewData["Title"] = "Add Samurai";
    Layout = null;
}
<!-- Modal -->
<div class="text-danger" asp-validation-summary="All"></div>
<form action="AddSamurai" id="form" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">

    <div class="form-group mb-3">

        <input type="text" id="samuraiName" class="form-control" asp-for="Name" placeholder="Samurai Name" />
        <span asp-validation-for="Name" class="text-danger"></span>

    </div>

    <div class="mb-3">
        <div>
            <input type="text" id="samuraiQuote" class="form-control" asp-for="Quote" placeholder="Featured Quote" />
            <span asp-validation-for="Quote" class="text-danger"></span>
        </div>

    </div>

    <div class="mb-3">
        <div class="form-outline">
            <textarea id="samuraiStory" class="form-control" asp-for="ShortStory" placeholder="Story" rows="4"></textarea>
            <span asp-validation-for="ShortStory" class="text-danger"></span>
        </div>
    </div>

    <div class="mb-3 form-check">
        <div class="modal-footer">
            <input type="submit" class="btn btn-dark my-color" value="Submit"/>
        </div>
    </div>
</form>

@section Scripts{
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Upskillz.Web/Views/Samurai/AllSamurais.cshtml
@model IEnumerable<Samurai>;
@inject SignInManager<AppUser> signInManager;

@{
    ViewData["Samurais"] = "AllSamurais";
    var user = await signInManager.UserManager.GetUserAsync(User);
    IEnumerable<string> roles = null;
    if (user != null)
    {
        roles = await signInManager.UserManager.GetRolesAsync(user);
    }
}

<section class="container pt-5 pb-5">
    <div class="col-12 d-flex justify-content-center align-content-center py-3">
        <div class="text-center align-content-center" style="width:80px; height:80px; border-radius:50px; background:#fff">
            <img src="~/assets/img/logo.png" style="width:80px; height:80px; margin-top:20px" alt="Alternate Text" />
        </div>
    </div>
    <div class="row">
        <h5 class="text-center align-content-center pt-2 pb-3"><em>Search your favourite Samurai and see what your legend has to say...</em></h5>
    </div>
    <div class="container pb-5" style="max-width: 1020px">
        <form method="get" action="@Url.Action("AllSamurais")" data-samurai-ajax="true" data-samurai-target="#samuraiList">
            <div class="input-group mb-3">
                <input type="search" name="searchTerm" data-samurai-autocomplete="@Url.Action("Autocomplete")" class="form-control" placeholder="Enter Sanurai's name" />
                <input class="input-group-text" type="submit" id="basic-addon2" value="Seach By Name" />
            </div>
        </form>
        <div class="row pt-5">
            <div class="d-flex justify-content-between">
                <h4>
                    List of Samurais
                </h4>
                @if (roles != null && roles.Contains("Admin"))
                {
                    <!-- Click on Modal Button -->
                    <a class="btn" onclick="showInPopup('@Url.Action("AddSamurai", "Samurai", null, Context.Request.Scheme)', 'Add a Samurai')">
                        <span>
                            <img src="https://img.icons8.com/ios-glyphs/120/000000/add--v2.png" style="width:40px; height:40px;" />
                        </span>
                    </a>
                }
            </div>
        </div>

        <hr style="height: 2px;" />

        <div id="samuraiList" class="row row-cols-1 row-cols-md-2 g-4">
            @await Html.PartialAsync("_SamuraiList", Model)
        </div>
    </div>
</section>

Upskillz.Web/Views/Samurai/SamuraiDetails.cshtml
@model SamuraiViewModel
@{
    ViewData["Samurais"] = "SamuraiDetails";
    var singleQuote = Model.Quotes.FirstOrDefault();
}

<section class="container pt-5 pb-5">
    <div class="container pt-5 pb-5">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="Samurai" asp-action="AllSamurais">Samurais</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Details</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-4 pb-3">
                <div class="img-fluid">
                    <img src="@Model.ImageUrl" style="width: 350px; height: 400px;" />
                </div>
            </div>
            <div class="col-sm-12 col-md-8 pb-3">
                <h3 class="text-left">@Model.Name</h3>
                <p class="" style="text-align: justify">@Model.Story</p>
                <figure class="text-center">
                    <blockquote class="blockquote">
                        <p>@singleQuote.Text</p>
                    </blockquote>
                    <figcaption class="blockquote-footer">
                        <cite>@Model.Name</cite>
                    </figcaption>
                </figure>
                <blockquote class="blockquote">
                    <p></p>
                </blockquote>
            </div>
        </div>
        <div class="row mt-5">            
            <h4 class="text-center mb-3">Other notable Qoutes from @Model.Name: </h4>            

            @for (var i = 1; i < @Model.Quotes.Count(); i++)
            {
                <div class="card mb-2">
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>@Model.Quotes[i].Text</p>
                        </blockquote>
                    </div>
                </div>
            }


        </div>

    </div>
</section>

Upskillz.Web/Views/Samurai/_SamuraiList.cshtml
@model IEnumerable<Samurai>;

@foreach (var samurai in Model)
{
    <div class="col-sm-4 py-3">
        <div class="card h-100">
            <div class="card-body">
                <h3 class="card-title">@samurai.Name</h3>
                <p class="card-text"><em>@samurai.Quotes.FirstOrDefault().Text.</em></p>
            </div>
            <div class="card-footer d-md-block">
                <a asp-controller="Samurai" asp-action="SamuraiDetails" asp-route-samuraiId="@samurai.Id" class="btn btn-dark btn-block">Go somewhere</a>
            </div>
        </div>
    </div>
}